# Generated by Django 3.0.7 on 2022-08-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('subCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PhoneItems',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('ram', models.IntegerField(max_length=5)),
                ('storage_capacity', models.IntegerField(max_length=5)),
                ('operating_system', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=12)),
                ('sim', models.CharField(max_length=7)),
                ('battery', models.IntegerField(max_length=10)),
                ('camera', models.CharField(max_length=8)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopItems',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('ram', models.IntegerField(max_length=5)),
                ('storage_capacity', models.IntegerField(max_length=5)),
                ('operating_system', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=12)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='JobsandSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('years_of_experience', models.IntegerField(max_length=20)),
                ('requirements', models.TextField(max_length=20)),
                ('responsibilities', models.TextField(max_length=20)),
                ('qualification', models.TextField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='HousingandHotelRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom', models.CharField(max_length=100)),
                ('bedroom', models.CharField(max_length=20)),
                ('furnished', models.CharField(max_length=20)),
                ('parking_spaces', models.CharField(max_length=20)),
                ('pets', models.CharField(max_length=20)),
                ('service_charge', models.CharField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='HousesandProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100)),
                ('type_of_property', models.CharField(max_length=20)),
                ('furnished', models.CharField(max_length=20)),
                ('parking_spaces', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='HealthandBeauty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FoodandDrinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FashionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('size', models.TextField(max_length=10)),
                ('sleeve_lenght', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=12)),
                ('condition', models.CharField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsandMobilephonesAcessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarsandAutomobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=20)),
                ('milleage', models.IntegerField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
    ]
