# Generated by Django 3.0.7 on 2022-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subCategory', '0002_auto_20220824_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsandautomobile',
            name='milleage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carsandautomobile',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobsandskills',
            name='years_of_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='battery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='storage_capacity',
            field=models.IntegerField(),
        ),
    ]
