# Generated by Django 3.0.7 on 2022-08-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subCategory', '0003_auto_20220824_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopitems',
            name='ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptopitems',
            name='storage_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
