# Generated by Django 3.0.7 on 2022-08-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subCategory', '0004_auto_20220824_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthandbeauty',
            old_name='color',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='healthandbeauty',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='healthandbeauty',
            name='type',
        ),
        migrations.CreateModel(
            name='FurnitureandAppliacnes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.ItemSubCategory')),
            ],
        ),
    ]
