# Generated by Django 3.0.7 on 2022-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subCategory', '0005_auto_20220824_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopitems',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
