# Generated by Django 3.0.7 on 2022-08-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subCategory', '0006_auto_20220824_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopitems',
            name='item_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_subcategory', to='subCategory.ItemSubCategory'),
        ),
        migrations.CreateModel(
            name='FinalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.LaptopItems')),
                ('phone_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.PhoneItems')),
            ],
        ),
    ]
