# Generated by Django 3.0.7 on 2022-08-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220827_1944'),
        ('subCategory', '0007_auto_20220826_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Products'),
        ),
    ]
