# Generated by Django 3.0.7 on 2022-08-31 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220827_1944'),
        ('subCategory', '0009_auto_20220829_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Products'),
        ),
    ]
