# Generated by Django 3.2.5 on 2022-09-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_stores_product'),
        ('product', '0007_alter_products_likes'),
        ('subCategory', '0013_alter_laptopitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopitems',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.products'),
        ),
        migrations.AlterField(
            model_name='laptopitems',
            name='store_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='stores.stores'),
        ),
    ]
