# Generated by Django 3.2.5 on 2022-09-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_products_likes'),
        ('subCategory', '0015_alter_laptopitems_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopitems',
            name='product',
        ),
        migrations.AddField(
            model_name='laptopitems',
            name='product',
            field=models.ManyToManyField(related_name='product', to='product.Products'),
        ),
    ]
