# Generated by Django 3.0.7 on 2022-08-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subCategory', '0007_auto_20220826_2211'),
        ('product', '0002_auto_20220823_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.subCategory'),
        ),
    ]
