# Generated by Django 3.2.5 on 2022-09-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_alter_review_reviewed_by'),
        ('product', '0005_productlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reviews.review'),
        ),
    ]
