# Generated by Django 3.2.5 on 2022-10-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_remove_stores_category'),
        ('product', '0007_alter_products_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
                ('operating_system', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productproperties', to='product.products')),
                ('store_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.stores')),
            ],
        ),
    ]
