# Generated by Django 3.2.5 on 2022-09-26 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reviews', '0007_alter_review_reviewed_by'),
        ('subCategory', '0015_alter_laptopitems_id'),
        ('stores', '0005_alter_stores_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapiItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
                ('operating_system', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=12)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finaltest_item_subcategory', to='subCategory.itemsubcategory')),
                ('store_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='images/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finaltest_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='finaltestimages', to='finaltest.ProductImageFile')),
                ('likes', models.ManyToManyField(blank=True, related_name='finaltestlikes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalowner', to=settings.AUTH_USER_MODEL)),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finaltest.lapiitems')),
                ('reviews', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalreviews', to='Reviews.review')),
                ('subCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finaltest_sub', to='subCategory.subcategory')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
