# Generated by Django 3.2.5 on 2022-09-15 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reviews', '0002_auto_20220915_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='negative_experience',
            field=models.ManyToManyField(related_name='negative_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='postive_experience',
            field=models.ManyToManyField(related_name='positive_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
