# Generated by Django 3.0.7 on 2022-08-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='things',
            name='images',
        ),
    ]
