# Generated by Django 3.0.7 on 2022-08-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_remove_things_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='images',
            field=models.ManyToManyField(related_name='images', to='things.Thingsfile'),
        ),
    ]
