# Generated by Django 3.2.5 on 2022-09-23 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_products_likes'),
        ('stores', '0005_alter_stores_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subCategory', '0015_alter_laptopitems_id'),
        ('Reviews', '0007_alter_review_reviewed_by'),
        ('things', '0004_auto_20220827_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='testimages', to='product.ProductImageFile')),
                ('likes', models.ManyToManyField(blank=True, related_name='testlikes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('reviews', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Reviews.review')),
                ('subCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sub', to='subCategory.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='LaptopItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
                ('operating_system', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=12)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_item_subcategory', to='subCategory.itemsubcategory')),
                ('store_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
            ],
        ),
    ]
