# Generated by Django 3.2.5 on 2022-09-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_laptopitems_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='things.laptopitems'),
        ),
    ]
