# Generated by Django 3.2.5 on 2022-09-26 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_stores_product'),
        ('product', '0007_alter_products_likes'),
        ('subCategory', '0015_alter_laptopitems_id'),
        ('Reviews', '0007_alter_review_reviewed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0006_products_prod_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaptopItems',
            new_name='TheLaptopItems',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='TheProducts',
        ),
        migrations.AlterField(
            model_name='theproducts',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subCategory.laptopitems'),
        ),
    ]
