# Generated by Django 3.2.5 on 2022-09-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_auto_20220926_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theproducts',
            options={'verbose_name_plural': 'products'},
        ),
    ]
