# Generated by Django 3.2.5 on 2022-09-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_alter_theproducts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theproducts',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='things.thelaptopitems'),
        ),
    ]
