# Generated by Django 3.2.5 on 2022-09-26 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reviews', '0007_alter_review_reviewed_by'),
        ('product', '0007_alter_products_likes'),
        ('stores', '0005_alter_stores_product'),
        ('subCategory', '0015_alter_laptopitems_id'),
        ('test', '0002_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='choicetestimages', to='product.ProductImageFile'),
        ),
        migrations.AddField(
            model_name='choice',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='choicetestlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choiceowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choicereviews', to='Reviews.review'),
        ),
        migrations.AddField(
            model_name='choice',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choicetest_sub', to='subCategory.subcategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='brand',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='color',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='condition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='item_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_test_item_subcategory', to='subCategory.itemsubcategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='operating_system',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='processor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='storage_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='store_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(default='inactive', max_length=10, null=True),
        ),
    ]
