# Generated by Django 3.2.5 on 2022-09-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_alter_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
    ]
