# Generated by Django 3.2.5 on 2022-09-27 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subCategory', '0015_alter_laptopitems_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0005_alter_stores_product'),
        ('test', '0007_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
                ('operating_system', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=12)),
                ('sim', models.CharField(max_length=7)),
                ('battery', models.IntegerField()),
                ('camera', models.CharField(max_length=8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_created_by', to=settings.AUTH_USER_MODEL)),
                ('item_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_items', to='subCategory.itemsubcategory')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choicephoneproducts', to='test.choice')),
                ('store_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_store_products', to='stores.stores')),
            ],
        ),
    ]
