# Generated by Django 3.2.5 on 2022-09-28 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reviews', '0007_alter_review_reviewed_by'),
        ('product', '0007_alter_products_likes'),
        ('subCategory', '0015_alter_laptopitems_id'),
        ('test', '0008_phoneitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, related_name='Second_choicetestimages', to='product.ProductImageFile')),
                ('likes', models.ManyToManyField(blank=True, related_name='Second_choicetestlikes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Second_choiceowner', to=settings.AUTH_USER_MODEL)),
                ('reviews', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Second_choicereviews', to='Reviews.review')),
                ('subCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Second_choicetest_sub', to='subCategory.subcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choicephoneproducts', to='test.secondchoice'),
        ),
    ]
