# Generated by Django 3.2.5 on 2022-09-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_auto_20220928_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneitems',
            old_name='product',
            new_name='details',
        ),
    ]
