# Generated by Django 3.2.5 on 2022-09-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_rename_product_phoneitems_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneitems',
            name='details',
        ),
        migrations.AddField(
            model_name='choice',
            name='pohone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test.phoneitems'),
        ),
    ]
