# Generated by Django 3.2.5 on 2022-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0013_alter_secondchoice_phoneitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneitems',
            name='battery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='brand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='camera',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='color',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='condition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='operating_system',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='processor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='sim',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='phoneitems',
            name='storage_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
