# Generated by Django 3.2.5 on 2022-09-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='user',
            new_name='owner',
        ),
    ]
