# Generated by Django 3.2.5 on 2022-09-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_user_stores_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='revews',
        ),
    ]
