# Generated by Django 3.2.5 on 2022-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_reviews'),
        ('stores', '0004_auto_20220919_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='product',
            field=models.ManyToManyField(to='product.Products'),
        ),
    ]
