# Generated by Django 3.2.5 on 2022-10-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_stores_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='product',
        ),
    ]
