# Generated by Django 3.0.7 on 2022-08-31 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='ImageBanner/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='images', to='banner.ProductImage')),
            ],
        ),
    ]
